# Generated by Django 4.2.7 on 2026-06-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_bloodrequest_bystander_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='bystander_phone',
        ),
        migrations.AlterField(
            model_name='donationresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('missed', 'Missed'), ('not_needed', 'Not Needed')], default='pending', max_length=12),
        ),
    ]
