# Generated by Django 4.2.7 on 2026-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_remove_bloodrequest_bystander_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='bystander_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='bystander_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
